using Asasy.Service.DashBoard.Contract.HomeInterfaces;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Asasy.Controllers.DashBoard
{
    [Authorize]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    //[Route("[controller]/[action]")]
    public class HomeController : Controller
    {
        private readonly IHomeServices _homeServices;

        public HomeController(IHomeServices homeServices = null)
        {
            _homeServices = homeServices;
        }

        public IActionResult Index()
        {
            var data = _homeServices.HomeIndex();

            return View(data);
        }
    }
}
